### ISSUE TITLE
支持RawTx的获取

### ISSUE THREAD

**Issue by baryon** [KaKeimei/meta-sv#1]
希望支持RawTx的获取，而不是下面API这样解析过
https://doc.metasv.com/#dfe799947f

实现上可以参考
https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get
加一个verbose参数。或者另外提供一个API

最好一些字段名也是兼容的， 比如vin 而不是 vinList

**Comment by KaKeimei** [comment]
RawTx获取的接口正在开发，近几天就会发布。

**Comment by KaKeimei** [comment]
字段名兼容不太容易，因为和我们数据结构相关，vin是List中的一个成员。
而且已经发布的接口定义修改可能会给其他开发者带来麻烦，希望理解

**Comment by KaKeimei** [comment]
https://api.metasv.com/v1/tx/8e3da3d115a685ae28421b5661517e829e495091e6121c8d4b0cd52531a660a2/raw

已经支持生交易查询
