### ISSUE TITLE
又一个需求

### ISSUE THREAD

**Issue by blue459** [KaKeimei/meta-sv#11]
希望添加一个基于metanet的查询 从tx获取rootTx接口。

**Comment by KaKeimei** [comment]
这个可以支持，我们尽快对应

**Comment by baryon** [comment]
望把需求概要写在标题上

**Comment by blue459** [comment]
> 望把需求概要写在标题上

好的~下次写上去

**Comment by KaKeimei** [comment]
https://metasv.com/#txid

已经在txid查询node的接口上增加了rootAddress和rootTxid
