### ISSUE TITLE
UTXO一览数据不正确

### ISSUE THREAD

**Issue by baryon** [KaKeimei/meta-sv#12]
https://doc.metasv.com/#utxo-2
今天开始这个API返回的数据不是最新的，导致交易发送失败。
好像返回的是旧数据

**Comment by baryon** [comment]
utxo_select似乎是对的，原因不明

**Comment by KaKeimei** [comment]
今天我们迁移到一个采用新的算法的utxo库里，现在还有2000块左右没有追上，请稍等一下。造成麻烦请多谅解

**Comment by KaKeimei** [comment]
utxo数据现已恢复正常，给你们造成麻烦请多谅解
