### ISSUE TITLE
数据编码应该是HEX而不是base64

### ISSUE THREAD

**Issue by baryon** [KaKeimei/meta-sv#2]
一些API返回的数据，比如lockScript的编码是base64，应该改成HEX，更自然，方便客户端处理。

**Comment by KaKeimei** [comment]
收到，这里采用base64编码是为了在巨大交易的情况下减少数据传输。这里考虑到开发者的使用方便，我们还是改回成HEX

**Comment by KaKeimei** [comment]
所有涉及生数据的地方已经修改为HEX
