### ISSUE TITLE
交易一览里缺少height

### ISSUE THREAD

**Issue by baryon** [KaKeimei/meta-sv#3]
下面这个API返回的数据中缺少高度
https://doc.metasv.com/#41844c4cf8

如果交易已经被打包应该显示实际高度，如果还在mempool，高度返回0

**Comment by KaKeimei** [comment]
收到，可以在接口返回值中加入height字段

**Comment by yaochaoutokyo** [comment]
已经在返回值中增加高度字段，未确认高度我们采用的是-1，因为块高度是从0号开始的

**Comment by baryon** [comment]
现有数据还需要做个batch处理一下，目前所有数据height都返回-1

**Comment by baryon** [comment]
当数据超过50条，一览是否可以知道还有多少未读？或者有个标志说明还有数据也行，那样客户端再调用一下api？

**Comment by baryon** [comment]
如果同时缺少inputAddress和protocol会把所有数据拉下来。应该避免，要求必须有一个参数

**Comment by KaKeimei** [comment]
> 如果同时缺少inputAddress和protocol会把所有数据拉下来。应该避免，要求必须有一个参数

这个也是一个功能，不加任何限制选取data

**Comment by KaKeimei** [comment]
> > 当数据超过50条，一览是否可以知道还有多少未读？或者有个标志说明还有数据也行，那样客户端再调用一下api？
> 
> 现在的机制也可以读取，每次判断一下，是否为50个

可以判断一下，不足50个就不用再翻页了

**Comment by baryon** [comment]
> > 如果同时缺少inputAddress和protocol会把所有数据拉下来。应该避免，要求必须有一个参数
> 
> 这个也是一个功能，不加任何限制选取data

不加限制，会有人把你们所有数据都取下来
