### ISSUE TITLE
交易详情查询出错未返回信息

### ISSUE THREAD

**Issue by baryon** [KaKeimei/meta-sv#4]
交易详情查询
https://doc.metasv.com/#dfe799947f
不存在的交易，返回
`
{
  code: 200,
  data: { txDetail: null, vinList: null, voutList: null },
  message: null,
  success: true
}
`
这里应该返回出错信息，否则客户端要去判断txDetail是否为null

**Comment by KaKeimei** [comment]
收到，如果交易不存在，code可以返回404

**Comment by KaKeimei** [comment]
[https://api.metasv.com/v1/tx/8e3da3d115a685ae28421b5661517e829e495091e6121c8d4b0cd52531a660a](错误交易详情)

交易详情不存在时，返回code 404
