### ISSUE TITLE
挑选UTXO API，当需要的amount太多时，应该返回目前的所有uxto

### ISSUE THREAD

**Issue by baryon** [KaKeimei/meta-sv#7]
https://doc.metasv.com/#utxo

```
{
    "code": xxxxx,
    "data": [
        {
            "outputIndex": 0,
            "address": "12higDjoCCNXSA95xZMWUdPvXNmkAduhWv",
            "txid": "0a21079a06c523fed3a41f890c4e96bb148433c90bf42d3c12649846af20f5b6",
            "id": 31537708,
            "ancestors": 0,
            "value": 1000,
            "height": 576232
        },
        {
            "outputIndex": 0,
            "address": "12higDjoCCNXSA95xZMWUdPvXNmkAduhWv",
            "txid": "166a3ab4254f7dbb0a9ea5750bdc19254fb8597b30a8c393b8a48d3f73939775",
            "id": 20292332,
            "ancestors": 0,
            "value": 666,
            "height": 576241
        },
    ],
    "message": 'utxo total amount is insufficient, request is 12345, while total is 1666',
    "success": false
}
```
因为构建交易时很难准确计算需要多少amount，即使不足预估值，也应该允许客户端之后调整

**Comment by KaKeimei** [comment]
有道理，我们会改进

**Comment by KaKeimei** [comment]
返回全量utxo有接口被攻击的风险，我们可以返回当前所有utxo的金额，以及utxo个数，方便应用估算手续费

**Comment by baryon** [comment]
那这个api就没法用，客户端只会调用另外一个api，自己设计挑选utxo算法

**Comment by yaochaoutokyo** [comment]
感谢反馈，这个接口原先的意图是帮助用户选择utxo，然后快速造交易，如果utxo不足那么就告知用户当前余额，通知用户余额不足。返回全量utxo不太符合我们这个接口的设计意图，如果有些用户误以为返回的utxo的意思是余额够可以造交易的话，直接使用了全量utxo，结果没有造成功。建议如果余额不够的场景的话，使用翻页获取utxo的接口，客户端选择utxo进行交易构造

**Comment by yaochaoutokyo** [comment]
感谢反馈，这个接口原先的意图是帮助用户选择utxo，然后快速造交易，如果utxo不足那么就告知用户当前余额，通知用户余额不足。返回全量utxo不太符合我们这个接口的设计意图，如果有些用户误以为返回的utxo的意思是余额够可以造交易的话，直接使用了全量utxo，结果没有造成功。而且返回全量utxo会留下攻击向量，例如，给一个utxo量巨大的地址，再给个不可能达到的目标余额，比如2100w bsv，那么每次请求都会给我们的数据带来巨大压力。

**Comment by KaKeimei** [comment]
如果查询全量utxo，建议用utxo select接口传入当前余额即可。如果第一次查询超过了余额，则系统会将当前余额返回，请用正确的余额再次尝试一下就可以取出所有utxo。

```
{
  "code": 20001,
  "data":{"balance": 1000000},
  "message": "whatever",
  "success": false
}
```
